version: '3.9'
services:

  website_server:
    image: node:lts
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    expose:
      - '6443'
    networks:
      - default
    volumes:
      - ./:/home/node/app
    command: 'npm start'

  webserver_website:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt/live/kenzieslist.com
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - website_server
    networks:
      - default 

networks:
  default:

volumes:
  web-root:
  certbot-etc:
  certbot-var: