version: '3.9'
services:

  kslist:
    hostname: kslist
    user: server
    build: .
    env_file: .env
    expose:
      - '3000'
    networks:
      - default
    volumes:
      - ./:/home/node/app
      - ./cache:/root/.cache

  webserver:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "2443:2443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt/live/kslist.org
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - kslist
    networks:
      - default 

networks:
  default:

volumes:
  web-root:
  certbot-etc:
  certbot-var: